spring:
  main:
    banner-mode: off
#  threads:
#    virtual:
#      enabled: true
  application:
    name: {{MAVEN_ARTIFACT_ID}}
  datasource:
    #    https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/  spring.datasource.hikari.
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: seal
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        metadata:
          # Don't modify it
          # 不要修改它
          main-zone-env: ${seal.kiss.env.main:DAILY}
          sub-set-zone-env: ${seal.kiss.env.subSet:}
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
# https://sca.aliyun.com/docs/2022/user-guide/nacos/advanced-guide/#springcconfigimport-%E5%BC%95%E5%85%A5
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:${spring.application.name}-${seal.kiss.env.gray:}.yml

# mybatis config
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: {{MAVEN_PACKAGE_NAME}}.integration.db
  #  type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  defaultCount: true
