spring:
  threads:
    virtual:
      enabled: true
  application:
    name: {{MAVEN_ARTIFACT_ID}}
  datasource:
#    https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/  spring.datasource.hikari.
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: seal
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis config
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: {{MAVEN_PACKAGE_NAME}}.integration.db
  #  type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  defaultCount: true


management:
  tracing:
    sampling:
      probability: 1.0