seal:
  kiss:
#    env:
#      run: DAILY
#      gray: GRAY_TEST
    gray:
      routesRule:
        static-source:
          modifyType: GRAY_PATH
          keyFromType: FROM_HEADER
          calculateType: IN
          inValues: ["1", "2"]
          targetGrayFlag: gray
        nacos-metadata:
          modifyType: GRAY_ENV
          keyFromType: FROM_HEADER
          calculateType: IN
          inValues: [ "1", "2" ]
          targetGrayFlag: gray
    path-limit:
      routeRules:
        static-source:
          # 只有静态资源可以这样使用
          allAllow: true
        nacos-metadata:
          pathRules:
            # 全路径，每接口都填写
            - method: POST
              path: /nacos/a
              needAuth: true
            - method: POST
              path: /nacos/ab
              needAuth: false

spring:
  application:
    name: seal-kiss-gateway

  cloud:
    gateway:
      routes:
      - id: static-source
        uri: http://127.0.0.1
        predicates:
          - Path=/static/**
        filters:
        - name: StripPrefix
          args:
            parts: 1
      - id: nacos-metadata
        uri: lb://seal-kiss-multi
        predicates:
          - Path=/nacos/**
        filters:
          - name: PrefixPath
            args:
              prefix: /aa
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  tracing:
    enabled: true
    sampling:
      probability: 1

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug