seal:
  kiss:
#    env:
#      main: DAILY
#      subSet: GRAY_TEST
    gray:
      routesRule:
        static-source:
          modifyType: GRAY_PATH
          keyFromType: FROM_HEADER
          calculateType: IN
          inValues: ["1", "2"]
          targetGrayFlag: gray
        nacos-metadata:
          modifyType: GRAY_ENV
          keyFromType: FROM_HEADER
          calculateType: IN
          inValues: [ "1", "2" ]
          targetGrayFlag: gray
        seal-kiss-multi:
          modifyType: GRAY_ENV
          keyFromType: FROM_HEADER
          calculateType: IN
          inValues: [ "1", "2" ]
          targetGrayFlag: gray
    auth-path-limit:
      routeRules:
        static-source:
          # 只有静态资源可以这样使用
          allAllow: true
        nacos-metadata:
          pathRules:
            # 全路径，每接口都填写
            - method: POST
              path: /nacos/a
              needAuth: true
            - method: POST
              path: /nacos/ab
              needAuth: false
        seal-kiss-multi:
          pathRules:
            - method: POST
              path: /demo/callBipartite
    rate-path-limit:
      routeRates:
        seal-kiss-multi:
          pathRates:
#            - path: /demo/callBipartite
#              replenishRate: 1
#              burstCapacity: 2
#              requestedTokens: 50

spring:
  application:
    name: seal-kiss-gateway

  cloud:
    gateway:
      routes:
      - id: static-source
        uri: http://127.0.0.1
        predicates:
          - Path=/static/**
        filters:
        - name: StripPrefix
          args:
            parts: 1
      - id: nacos-metadata
        uri: lb://seal-kiss-multi
        predicates:
          - Path=/nacos/**
        filters:
          - name: PrefixPath
            args:
              prefix: /aa
      - id: seal-kiss-multi
        uri: lb://seal-kiss-multi
        predicates:
          - Path=/seal-kiss-multi/**
        filters:
          - name: StripPrefix
            args:
              parts: 1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 9090